name: Covenant Code Daily Update with Slack + JSON Log

on:
  workflow_dispatch:

jobs:
  generate-covenant-update:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Generate ChatGPT content (Markdown + JSON)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          mkdir -p daily_updates logs
          touch daily_updates/.keep logs/.keep

          RESPONSE_JSON=$(curl https://api.openai.com/v1/chat/completions \
            -s \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -d '{
              "model": "gpt-4o",
              "messages": [{
                "role": "user",
                "content": "Generate a test message for todays Covenant Code workflow run. Say Hello world."
                }],
              "max_tokens": 600
            }')

          RESPONSE_MARKDOWN=$(echo "$RESPONSE_JSON" | jq -r '.choices[0].message.content')

          DATE=$(date +%Y-%m-%d)
          MD_FILE="daily_updates/covenant_code_update_$DATE.md"
          JSON_FILE="logs/covenant_raw_response_$DATE.json"

          echo "$RESPONSE_MARKDOWN"_
