name: Covenant Code Daily Update with Slack + JSON Log

on:
  workflow_dispatch:

jobs:
  generate-covenant-update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Generate ChatGPT content (Markdown + JSON)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          mkdir -p daily_updates logs
          touch daily_updates/.keep logs/.keep

          RESPONSE_JSON=$(curl https://api.openai.com/v1/chat/completions \
            -s \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -d '{
              "model": "gpt-4o",
              "messages": [{
                "role": "user",
                "content": "Generate a test message for todays Covenant Code workflow run. Say Hello world."
              }],
              "max_tokens": 600
            }')

          RESPONSE_MARKDOWN=$(echo "$RESPONSE_JSON" | jq -r '.choices[0].message.content')

          DATE=$(date +%Y-%m-%d)
          MD_FILE="daily_updates/covenant_code_update_$DATE.md"
          JSON_FILE="logs/covenant_raw_response_$DATE.json"

          echo "$RESPONSE_MARKDOWN" > "$MD_FILE"
          echo "$RESPONSE_JSON" > "$JSON_FILE"
          echo "$RESPONSE_MARKDOWN"

      - name: Commit and push updates (only if changes exist)
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action Bot"
          git add daily_updates/ logs/
          if git diff --cached --quiet; then
            echo "🔸 No changes to commit. Skipping push."
          else
            git commit -m "Covenant Code update and raw log for $(date +'%Y-%m-%d')"
            git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/jschonberg01/convenantcode.git
            git push origin main
          fi

      - name: Post update to Slack
        if: env.SLACK_WEBHOOK_URL != ''
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          PAYLOAD=$(jq -n --arg text "*Covenant Code Update $(date +'%Y-%m-%d')*\n\n${RESPONSE_MARKDOWN}" '{text: $text}')
          curl -X POST -H 'Content-type: application/json' --data "$PAYLOAD" "$SLACK_WEBHOOK_URL"
